const PDFDocument = require('pdfkit');

exports.streamInvoicePdf = (payment, res) => {
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="invoice-${payment._id}.pdf"`);

  const doc = new PDFDocument({ margin: 50 });
  doc.pipe(res);

  doc.fontSize(20).text('Hospital AI Invoice', { align: 'center' });
  doc.moveDown();
  doc.fontSize(12).text(`Invoice ID: ${payment._id}`);
  doc.text(`Date: ${new Date(payment.createdAt).toLocaleDateString()}`);
  doc.text(`Status: ${payment.status}`);
  doc.text(`Payment Type: ${payment.paymentType}`);
  doc.text(`Payment Method: ${payment.paymentMethod}`);
  if (payment.transactionId) doc.text(`Transaction ID: ${payment.transactionId}`);
  doc.moveDown();
  doc.fontSize(14).text('Billing Details');
  doc.fontSize(12).text(`Patient: ${payment.patientId?.name || payment.patientId}`);
  doc.text(`Doctor: Dr. ${payment.doctorId?.name || payment.doctorId}`);
  if (payment.appointmentId?._id) doc.text(`Appointment ID: ${payment.appointmentId._id}`);
  doc.moveDown();
  doc.fontSize(16).text(`Amount Paid: ${payment.currency} ${payment.amount}`, { align: 'right' });
  doc.moveDown(2);
  doc.fontSize(10).fillColor('#666').text('Generated by Hospital AI Smart Healthcare System');
  doc.end();
};
