const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

const formatConfidence = (confidence) => {
  if (confidence === undefined || confidence === null) return 'N/A';
  return confidence > 1 ? `${confidence}%` : `${(confidence * 100).toFixed(0)}%`;
};

const generatePDFReport = (appointmentData, patientName, doctorName, report = null) => {
  return new Promise((resolve, reject) => {
    try {
      const reportsDir = path.join(__dirname, '../reports');

      if (!fs.existsSync(reportsDir)) {
        fs.mkdirSync(reportsDir, { recursive: true });
      }

      const filename = `report-${Date.now()}.pdf`;
      const filepath = path.join(reportsDir, filename);
      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      const stream = fs.createWriteStream(filepath);
      doc.pipe(stream);

      doc.fontSize(24).font('Helvetica-Bold').text('Medical Report', { align: 'center' });
      doc.moveDown(0.5);
      doc.fontSize(10).font('Helvetica').text('Smart AI Health Management System', { align: 'center' });
      doc.moveTo(50, 100).lineTo(550, 100).stroke();
      doc.moveDown(0.5);

      doc.fontSize(12).font('Helvetica-Bold').text('Patient Information:', { underline: true });
      doc.fontSize(10).font('Helvetica').text(`Name: ${patientName}`);
      doc.text(`Date: ${new Date().toLocaleDateString()}`);
      doc.moveDown(0.3);

      doc.fontSize(12).font('Helvetica-Bold').text('Consulting Doctor:', { underline: true });
      doc.fontSize(10).font('Helvetica').text(`Name: ${doctorName}`);
      doc.moveDown(0.3);

      doc.fontSize(12).font('Helvetica-Bold').text('Reported Symptoms:', { underline: true });
      doc.fontSize(10).font('Helvetica');
      (appointmentData.symptoms || []).forEach(symptom => doc.text(`- ${symptom}`));
      doc.moveDown(0.3);

      doc.fontSize(12).font('Helvetica-Bold').text('AI Triage:', { underline: true });
      doc.fontSize(10).font('Helvetica');
      doc.text(`Predicted Condition: ${appointmentData.aiPrediction?.disease || 'N/A'}`);
      doc.text(`Confidence Level: ${formatConfidence(appointmentData.aiPrediction?.confidence)}`);
      doc.text(`Severity: ${appointmentData.aiPrediction?.severity || 'N/A'}`);
      doc.text(`Urgency: ${appointmentData.aiPrediction?.urgency || 'N/A'}`);
      doc.text(`Recommended Department: ${appointmentData.aiPrediction?.recommendedDepartment || 'N/A'}`);
      doc.moveDown(0.3);

      if (appointmentData.aiPrediction?.isEmergency) {
        doc.fillColor('#FF0000');
        doc.fontSize(11).font('Helvetica-Bold').text('EMERGENCY CASE - PRIORITY TREATMENT REQUIRED');
        doc.fillColor('#000000');
        doc.moveDown(0.3);
      }

      if (report || appointmentData.diagnosis) {
        doc.fontSize(12).font('Helvetica-Bold').text('Doctor Diagnosis:', { underline: true });
        doc.fontSize(10).font('Helvetica').text(report?.diagnosis || appointmentData.diagnosis || 'Not provided');
        doc.moveDown(0.3);
      }

      const medicines = report?.medicines || appointmentData.prescription?.medicines || [];
      if (medicines.length > 0) {
        doc.fontSize(12).font('Helvetica-Bold').text('Medicines:', { underline: true });
        doc.fontSize(10).font('Helvetica');
        medicines.forEach((medicine, index) => {
          doc.text(`${index + 1}. ${medicine.name || ''} ${medicine.dosage || ''} - ${medicine.frequency || ''} - ${medicine.duration || ''}`);
          if (medicine.instructions) doc.text(`   Instructions: ${medicine.instructions}`);
        });
        doc.moveDown(0.3);
      }

      doc.fontSize(12).font('Helvetica-Bold').text('Advice:', { underline: true });
      doc.fontSize(10).font('Helvetica');
      doc.text(report?.advice || appointmentData.prescription?.advice || 'Follow doctor advice and schedule follow-up if symptoms continue.');
      doc.moveDown(0.3);

      doc.moveTo(50, 700).lineTo(550, 700).stroke();
      doc.fontSize(8).font('Helvetica').text(
        'Generated by Smart AI Health Management System. This document supports consultation and does not replace emergency care.',
        50,
        710,
        { align: 'center' }
      );

      doc.end();

      stream.on('finish', () => resolve({ success: true, filename, filepath }));
      stream.on('error', reject);
    } catch (error) {
      reject(error);
    }
  });
};

module.exports = { generatePDFReport };
